### ISSUE TITLE
odd code generation

### ISSUE THREAD

**Issue by AlonzoTG** [mono/VulkanSharp#10]
Thanks for responding so shockingly immediately to last night's bug.

My expired trial version of a code checker flagged this little function as always returning false: 

#############################################

		public Bool32 GetSurfaceSupportKHR (UInt32 queueFamilyIndex, SurfaceKhr surface)
		{
			Result result;
			Bool32 pSupported;
			unsafe {
				pSupported = new Bool32 ();
				result = Interop.NativeMethods.vkGetPhysicalDeviceSurfaceSupportKHR (this.m, queueFamilyIndex, surface.m, &pSupported);
				if (result != Result.Success)
					throw new ResultException (result);

				return pSupported;
			}
		}
#############################################

I'm trying to compile against .net 4.6. It's giving me grief about sizeof<>() ... but I'd tend to ignore most of those...

**Comment by radekdoulik** [comment]
From quick look this seems OK to me, the vkGetPhysicalDeviceSurfaceSupportKHR is called with pointer to pSupported and can modify the pSupported value.
