### ISSUE TITLE
Out parameters and redundant alloc:

### ISSUE THREAD

**Issue by AlonzoTG** [mono/VulkanSharp#11]
About a dozen such functions do this: 

########################
		public void ResetFences (UInt32 fenceCount, Fence pFences)
		{
			Result result;
			unsafe {
				pFences = new Fence ();

				fixed (UInt64* ptrpFences = &pFences.m) {
					result = Interop.NativeMethods.vkResetFences (this.m, fenceCount, ptrpFences);
				}
				if (result != Result.Success)
					throw new ResultException (result);
			}
		}
########################

which should mark pfences as "out"

I really don't know the convention here. Is the object supposed to be allocated and returned or is the caller supposed to provide the object where the allocation would be redundant? Anyway, my tool is flagging this.

**Comment by radekdoulik** [comment]
Not everything is done yet. We are still developing rapidly. That method should return Fence[] in future.

**Comment by radekdoulik** [comment]
Looked at it closer today, and it actually should not return fences, the pFences parameter is const, so it shouldn't create new fences at all. I will fix that.
