### ISSUE TITLE
No entry point towards 'vkCreateInstance'.

### ISSUE THREAD

**Issue by Zurkloyd** [mono/VulkanSharp#12]
Hello developers behind VulkanSharp!

I came to report an issue today that held me back from creating a Vulkan application.
The error is as following: 

> An unhandled exception of type 'System.EntryPointNotFoundException' occurred in Vulkan.dll
> Additional information: Unable to find an entry point named 'vkCreateInstance' in DLL 'vulkan'. 

I added an image on which Visual Studio gives me the error code. I hope this can be of any help. 

![vulkanerror_001](https://cloud.githubusercontent.com/assets/5000504/15189961/c6b5c6ec-17ad-11e6-87d1-d59f7d164f21.PNG)

**Comment by radekdoulik** [comment]
I didn't try VulkanSharp on Windows yet. Are you sure you have Vulkan installed?

**Comment by Zurkloyd** [comment]
@radekdoulik Yes, I have both the VulkanSDK and the Vulkan Runtime installed. I can run native Vulkan applications as well as an other C# vulkan wrapper as well. The other wrapper is a lot of work to implement but does run.

I launched Visual Studio again for about 10 minutes and went messing around a bit more. This time the same 'EntryPointNotFound exception pointed towards one of the generated files.

![vulkanerror_002](https://cloud.githubusercontent.com/assets/5000504/15401759/3c3ddd34-1df1-11e6-91bd-f0de54c8ab5f.PNG)

**Comment by radekdoulik** [comment]
It probably means it cannot find the vulkan native library.

I hope to try VulkanSharp on windows soon.

**Comment by bholcomb** [comment]
I noticed that this library is trying to use the "vulkan" library for pinvoke, but on my windows system, it looks like the dll that should be used is "vulkan-1".  Could this be causing the issue?

**Comment by Zurkloyd** [comment]
I changed the 'generator' locally a bit to use 'vulkan-1.dll' instead of 'vulkan' and it did result in some progress. It seems like the function now gets called. So the wrapper was pointing at the wrong library after all. 

![vulkanerror_004](https://cloud.githubusercontent.com/assets/5000504/15407821/451c1ae4-1e0d-11e6-8134-de756574ec53.PNG)

Time to continue to explore this and attempt to build a basic application.

![vulkanerror_003](https://cloud.githubusercontent.com/assets/5000504/15407785/0690b730-1e0d-11e6-83bb-de3df84189f6.PNG)

**Comment by radekdoulik** [comment]
I think "vulkan-1" instead of vulkan-1.dll would be enough. I guess I can change it to vulkan-1 so that it works on Windows and use dllmap on Android and Linux to map to vulkan

**Comment by radekdoulik** [comment]
this should be fixed now
