### ISSUE TITLE
vk*EXT do not work

### ISSUE THREAD

**Issue by AlexHild** [mono/VulkanSharp#21]
Tested CreateDebugReportCallbackEXT and DebugReportMessageEXT, both fail due to missing entry point. Calling them via GetProcAddress works.

**Comment by radekdoulik** [comment]
I have code for this, just need to clean it. I have also sample to use it with verification layers which I plan to publish soon.

**Comment by radekdoulik** [comment]
Alex, I think you missed my comment https://github.com/mono/VulkanSharp/pull/17#issuecomment-223582576

Could you please try to sign it again, looks like it wasn't recorded the first time.

**Comment by AlexHild** [comment]
For now I have my own implementation to test validation layer. Works fine. Thanks for all your work!

P.S.: Answered your comment in #17
