### ISSUE TITLE
make Instance disposable

### ISSUE THREAD

**Issue by pqnet** [mono/VulkanSharp#29]
Should `Instance` class be disposable, and executed `Destroy` at dispose time, since has ownership on unmanaged resources?

**Comment by radekdoulik** [comment]
Yes. We are also leaking some memory. I hope to fix it soon.

**Comment by krasnotsvetov** [comment]
One of the case of leaking memory here:
If i use EnableDebug(), Instanse never calls DestroyDebugReportCallbackEXT for DebugReportCallbackExt.
