### ISSUE TITLE
Can't build. Missing vk.xml file.

### ISSUE THREAD

**Issue by michidk** [mono/VulkanSharp#31]
I can't build using Visual Studio or gnu make, because the vk.xml file is missing.
It is not contained in the VulkanSharp repo. Were do i find it?

**Comment by Jimmacle** [comment]
You can find it here: https://github.com/KhronosGroup/Vulkan-Docs/tree/1.0/src/spec

**Comment by michidk** [comment]
Thanks, I tried that file, and it failed, so I thought I might be using the wrong one.
Did anyone try building VulkanSharp on windows? Seems pretty difficult.

**Comment by Jimmacle** [comment]
I was able to build it but I'm having other issues with making the project work so I may have managed to do it wrong as well.
