### ISSUE TITLE
Generator does not properly generate code to calculate enum size

### ISSUE THREAD

**Issue by Jimmacle** [mono/VulkanSharp#32]
This method throws an exception when trying to calculate the size of the type "PresentModeKhr" which is an integer enum.

![image](https://cloud.githubusercontent.com/assets/6447556/17086549/39bad12e-51aa-11e6-8ee0-884a6b305f73.png)

**Comment by jonpryor** [comment]
The code generator should instead emit:

    int size = Marshal.SizeOf (Enum.GetUnderlyingType (typeof(PresentModeKhr)));

Alternatively, the generator should "know" the underlying enum type and inline it accordingly:

    int size = 4;

**Comment by Jimmacle** [comment]
I looked at the generator and the code that actually writes the line is [here](https://github.com/mono/VulkanSharp/blob/master/tools/Generator/Generator.cs#L1503). I looked through the code to see if I could fix it myself but it looks pretty complicated to me :stuck_out_tongue:

**Comment by jonpryor** [comment]
The "simple but not optimized" case would be to change:

	IndentWriteLine ("int size = Marshal.SizeOf (typeof ({0}{1}));", isInInterop ? "Interop." : "", dataParam.isHandle ? GetHandleType (handles [dataParam.csType]) : dataParam.csType);

to:

	IndentWriteLine ("int size = Marshal.SizeOf (Enum.GetUnderlyingType (typeof ({0}{1})));",
			isInInterop ? "Interop." : "",
			dataParam.isHandle ? GetHandleType (handles [dataParam.csType]) : dataParam.csType);

**Comment by Jimmacle** [comment]
Wouldn't that break the generated code for any array creation that isn't an array of enums?

**Comment by radekdoulik** [comment]
Thanks for looking into that. I have modified the generator to take care about the enums, so that should hopefully fix it.

**Comment by Jimmacle** [comment]
Confirmed working on Windows as well.
