### ISSUE TITLE
Any plans to release a nuget for this?

### ISSUE THREAD

**Issue by pglaspey** [mono/VulkanSharp#34]
Would be quite handy! Thanks.

**Comment by radekdoulik** [comment]
Yes, it is on my TODO list. Hope to get to it soon.

**Comment by radekdoulik** [comment]
please let me know whether the package works OK

**Comment by rglaspey** [comment]
thank you so much. I will test this out this weekend and let you know.

**Comment by pglaspey** [comment]
The nuget package works great. I do have an issue though. I am creating a GLFW 3.2 wrapper for vulkan and I cannot pass the intptr for some of the objects because they are internal. Is there a way these can made public (or an additional public property that exposes them?) so I can use them to pass to the GLFW wrapper?

The ones in question are Instance, Device, and SurfaceKhr (the m Properties).

**Comment by radekdoulik** [comment]
Thanks for the response. I added Handle property to expose the value. Hopefully that will work for you. 0.0.2 nuget package should have that.

**Comment by rglaspey** [comment]
Thank you.
