### ISSUE TITLE
Hide default constructors

### ISSUE THREAD

**Issue by tangmi** [mono/VulkanSharp#35]
It seems like many VulkanSharp objects created with the default constructor end up being invalid and should instead be made with their associated factory methods.

Should the default constructors for these objects (e.g. `PhysicalDevice`, `SurfaceKhr`, etc) be private or internal?

**Comment by Jimmacle** [comment]
The default constructors are currently the only way to create the equivalent of a null pointer, so if the constructors are hidden another way of creating/using null pointers needs to be added.

**Comment by tangmi** [comment]
I admittedly am learning Vulkan and don't have that much context here, but should we not just be allowing `null` to be passed in when a null pointer is needed? Or provide some helper factory that just creates opaque "null" objects?

**Comment by Jimmacle** [comment]
Of course, even just adding a static "NullHandle" property to the classes would be sufficient. It would make the intention a lot more clear, imo.

**Comment by tangmi** [comment]
I don't know how important it is to not do extra allocations, but having a static "NullHandle" will not do extra allocations as a bonus, I guess.

**Comment by jonpryor** [comment]
> having a static "NullHandle" will not do extra allocations as a bonus, I guess.

Depends on how `NullHandle` is constructed. There are (at least?) two plausible ways to go:

1. Return a cached value:

        class Example {
             static object nullHandle = new Whatever();
             public object NullHandle { get { return nullHandle; } }
        }

2. Return a new value:

        class Example {
             public object NullHandle { get { return new Whatever(); } }
        }

When talking about allocations, *what kind* of allocations are we concerned about? *Vulkan* object allocations? Or managed object allocations which contribute to GC effort?

(1) allocates a *single* object, which may be completely unnecessary. (2) allocates a new object on every invocation, which is plausibly counter to property convention, and allocates *more* memory.

At least with the default constructor you know when you're creating the *managed* objects...

**Comment by tangmi** [comment]
I imagine that using [`VK_NULL_HANDLE`](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VK_NULL_HANDLE.html) doesn't create any Vulkan object allocations, as the value seems to just be a special value that Vulkan treats as "null".

Ideally, we'll be able to just pass C#'s `null` into the wrappers and VulkanSharp will do the Right Thing™, no managed objects required when not necessary.

**Comment by radekdoulik** [comment]
We already allow passing null (like array parameters), there are still places I forgot to modify. Will fix that.

**Comment by tangmi** [comment]
I believe we can allow passing null anywhere a "Vulkan object" is needed by creating an interface that all objects (with handles) extend from (or a abstract base class if we want to keep the handles internal) and an extension method that retrieves the handle or `IntPtr.Zero`, if the object is null. All instances of `[object].m` could be replaced by `[object].GetHandle()`, or something similar.

    internal interface VKObject
    {
        IntPtr m { get; }
    }

    internal static class HandleExtension
    {
        internal static IntPtr GetHandle(this VKObject obj) => obj?.m ?? IntPtr.Zero;
    }
    
    public partial class Device : VKObject
    {
        // ...

Thoughts on this?

**Comment by tangmi** [comment]
Seems like the resolution of #37 will be related to this?

**Comment by radekdoulik** [comment]
We can do something similar like VkObject idea, we just need to do it for both handle types separately

**Comment by tangmi** [comment]
Nice! Thanks for the quick response!
