### ISSUE TITLE
Default "null" argument. Wrong generation.

### ISSUE THREAD

**Issue by krasnotsvetov** [mono/VulkanSharp#37]
Hello.
https://github.com/mono/VulkanSharp/blob/a83bcbe17876ab5fd8147ae865b38164a4462387/src/Vulkan/Handles.cs#L1612

You can see in this case, that default argument has "null" value, but then try take fence's member: fence.M that throw  NullPointerException(line 1621).

And some methods with same signature will throw NullPointerException too.

**Comment by tangmi** [comment]
It seems like to use `VK_NULL_HANDLE`, one should use the default constructor (i.e. `new Fence()`) in VulkanSharp

**Comment by krasnotsvetov** [comment]
Yes, I can use default constructor for fency, but it's looking strange to have default param "null" in this case.  
So if i don't have another way to use, for example, Queue.Submit, i think default argument should be removed or generator should be changed.

**Comment by radekdoulik** [comment]
Queue.Submit should now work OK with default null value
