### ISSUE TITLE
Overloading methods taking arrays of elements to also take single elements

### ISSUE THREAD

**Issue by AlexHild** [mono/VulkanSharp#39]
There are lots of functions taking arrays as arguments, which I often use with single elements.

For example vkCmdBindDescriptorSets takes an array of descriptor sets, but in most cases I only pass a single one. In all this cases I have to create an array for a single element. I guess this leads to lots of unnecessary array constructions and garbage collector runs.

Perhaps its possible to overload this functions to also take single elements.

**Comment by radekdoulik** [comment]
It is on the TODO list :-)

https://github.com/mono/VulkanSharp/blob/master/tools/Generator/NOTES.txt#L12

**Comment by AlexHild** [comment]
First, thanks for implementing this so quickly!

However, there are some problems with the new overloads in the moment:

CmdPipelineBarrier, UpdateDescriptorSets and possibly others take multiple array arguments. The count for these array arguments currently always is one even if null is passed.

The non array overload of CmdBindDescriptorSet can not be called without passing an pDynamicOffset. I think there are two solutions:
1) Create an additional overload without pDynamicOffset
2) Make pDynamicOffset nullable

**Comment by radekdoulik** [comment]
Hopefully this fixes it.

I have tested it with CmdBindDescriptorSet. Please let me know whether it works right with your code.

**Comment by AlexHild** [comment]
Thanks! All single element functions I am using work correctly now.
