### ISSUE TITLE
Generating bindings for Vulkan 1.0.25 fails

### ISSUE THREAD

**Issue by himanshugoel2797** [mono/VulkanSharp#43]
I don't know enough about the format used in the vk.xml file, however it seems that generating bindings for the latest revision of the Vulkan spec fails at WriteMemberArray because of being unable to find the 'len' member for a function pointer, specifically for pAcquireTimeoutMilliseconds: https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml#L2246

**Comment by himanshugoel2797** [comment]
I think this is because pAcquireTimeoutMilliseconds is meant to be (from what I can tell), a const uint32_t* but not an array, however, the Generator is unable to determine that and ends up calling WriteMemberArray.

**Comment by radekdoulik** [comment]
It should be now fully fixed by https://github.com/mono/VulkanSharp/commit/ddba19b025184f338160174a05cdad8d12832f90
