### ISSUE TITLE
Is it possible to use Vulkan .Net wrapper for mobiles??

### ISSUE THREAD

**Issue by Nikolsi** [mono/VulkanSharp#45]
My question is in header.  I couldn't find any information about Vulkan in Xamarin, probably it is not possible. However, is there any solutions to use .net Vulkan with mobile?

**Comment by radekdoulik** [comment]
It is possible. Check our Android [samples](https://github.com/mono/VulkanSharp/tree/master/samples)

Just install the nuget [package](https://www.nuget.org/packages/VulkanSharp), which contains Xamarin Android target framework. And should be ready to go.
