### ISSUE TITLE
Nuget package does not add reference to Vulkan.Windows.dll on windows plattforms

### ISSUE THREAD

**Issue by AlexHild** [mono/VulkanSharp#46]
The nuget package only adds Vulkan.dll to the project references on windows plattforms. I can imagine to possible solutions:

1) Automatically add Vulkan.Windows.dll on windows plattforms only (is this possible?)
2) Create a second nuget package for Vulkan.Windows.dll referencing the main VulkanSharp package.

**Comment by AlonzoTG** [comment]
AlexHild wrote:
>
> The nuget package only adds Vulkan.dll to the project references on
> windows plattforms. I can imagine to possible solutions:
>
> 1) Automatically add Vulkan.Windows.dll on windows plattforms only (is
> this possible?)
> 2) Create a second nuget package for Vulkan.Windows.dll referencing
> the main VulkanSharp package.
>

Yeah, that there is your generated library, take that and copy it into
whatever project you are doing and add it to it's references...

-- 
IQ is a measure of how stupid you feel.

Powers are not rights.

**Comment by AlexHild** [comment]
You are right, I can add Vulkan.Windows.dll by hand. It's just not very comfortable, as you have to update the manual reference after every update of the package.

**Comment by radekdoulik** [comment]
It works OK for me. Tried current https://www.nuget.org/packages/VulkanSharp package.

Do you use the latest nuget package? I added win8 target some time ago (https://github.com/mono/VulkanSharp/commit/67a59981d16befcff73cd0ccbde1b53a23892c3a)

Or maybe you use different target?

![screen shot 2016-09-06 at 14 48 21](https://cloud.githubusercontent.com/assets/4147484/18274102/20b30570-7441-11e6-8b57-43e1d510f8b2.png)

**Comment by AlexHild** [comment]
I'm referencing from a .NET 4.5.2 class library. The reference points to portable-net45+win8+MonoAndroid10 in my case.

I think it would work by adding a non-portable NET45 target as well.

**Comment by radekdoulik** [comment]
Could you attach a sample project? The Vulkan.Windows.dll is targeting win8, so I hoped that would work.

**Comment by radekdoulik** [comment]
I have added net452 target. Let see if it will help.

**Comment by radekdoulik** [comment]
OK, rereleased it, hopefully it is right this time. Please try 0.1.3 version.

**Comment by AlexHild** [comment]
Works for me. Thanks a lot!

**Comment by radekdoulik** [comment]
Great, thanks for confirmation!
