### ISSUE TITLE
Documentation generation

### ISSUE THREAD

**Issue by FacticiusVir** [mono/VulkanSharp#50]
If you're adding documentation, I've got a [preprocessed doc file](https://github.com/FacticiusVir/SharpVk-Docs/blob/master/Docs/vkDocs.xml) in the [SharpVk-Docs](https://github.com/FacticiusVir/SharpVk-Docs) repo that will save some duplication of effort parsing asciidoc.

**Comment by realvictorprm** [comment]
@facticiusvir Seems like no one is interested in it :smiley:

**Comment by realvictorprm** [comment]
Sad

Am 25.08.2017 16:19 schrieb "Andrew Armstrong" <notifications@github.com>:
