### ISSUE TITLE
vkCreateDebugReportCallbackEXT, vkDestroyDebugReportCallbackEXT and vkDebugReportMessageEXT

### ISSUE THREAD

**Issue by amerkoleci** [mono/VulkanSharp#54]
Those 3 need the "[UnmanagedFunctionPointer(CallingConvention.StdCall)]" otherwise GC marshalling will fail in some scenarios.

**Comment by discosultan** [comment]
Can you elaborate in which scenarios this may be a problem?

**Comment by amerkoleci** [comment]
Now I'm using your VulkanCore lib, should be considered closed, I thought the issue was to missing UnmanagedFunctionPointerAttribute.
