### ISSUE TITLE
ImageCreateFlags --- error CS1001: Identifier expected

### ISSUE THREAD

**Issue by plynkus** [mono/VulkanSharp#58]
Found: "error CS1001: Identifier expected" when compiling the repo tip.

Appears to relate to a leading "2D" being emitted in the final generated entry:

	[Flags]
	public enum ImageCreateFlags : int
	{
		SparseBinding = 0x1,
		SparseResidency = 0x2,
		SparseAliased = 0x4,
		MutableFormat = 0x8,
		CubeCompatible = 0x10,
		2DArrayCompatibleKhr = 0x20,
	}

...thus an invalid token.

This was built with the latest VS2017RC (not sure that matters).

**Comment by radekdoulik** [comment]
That's weird. On my system it is generated differently. Like this: https://github.com/mono/VulkanSharp/blob/master/src/Vulkan/Enums.cs#L453

Does it also happen when you rebuild whole project?

**Comment by plynkus** [comment]
Local issue, apparently.  Git reported a clean workspace against tip but was seeing the above---a complete wipe and re-clone has it back in order, apparently.  Apologies.

**Comment by radekdoulik** [comment]
Nice, thanks for confirming. Might be a dependency issue. Let me know if you run into it again.
