### ISSUE TITLE
What about switching Vulkan.dll to .NET Standard?

### ISSUE THREAD

**Issue by TillAlex** [mono/VulkanSharp#68]
As far as I understand PCLs are dead. Is switching Vulkan.dll to .NET Standard a good idea?

**Comment by radekdoulik** [comment]
It is good idea. There are some issues in Xamarin.Android and .NET standard right now though. Once they are fixed I am all for it.

**Comment by mellinoe** [comment]
@TillAlex I maintain some bindings [here](https://github.com/mellinoe/vk) which support .NET Standard. They are very different in style from the bindings here, though -- closer to native Vulkan.

**Comment by FacticiusVir** [comment]
@mellinoe Is vk compatible with Xamarin?

@TillAlex Most of the actively maintained .NET Vulkan libraries support .NET Standard; [vk](https://github.com/mellinoe/vk) is a great low-level implementation, I maintain [SharpVk](https://github.com/FacticiusVir/SharpVk) which is closer to VulkanSharp's API, and [VulkanCore](https://github.com/discosultan/VulkanCore) is a hand-coded binding specifically for .NET Core.

**Comment by mellinoe** [comment]
@FacticiusVir It should be compatible, yeah. But like @radekdoulik mentioned, there are some problems with Xamarin + .NET Standard at the moment.

**Comment by TillAlex** [comment]
Is any of those library tested with MoltenVK? I'm statically linking MoltenVK into my app. As I don't get dllmaps working I have to change the DllImports in code to make it working with VulkanSharp.

**Comment by mellinoe** [comment]
@TillAlex I've tested my library with MoltenVK, but not on mono/Xamarin. Only on .NET Core/macOS.
