### ISSUE TITLE
CmdDrawIndexed not drawing as expected

### ISSUE THREAD

**Issue by Amatsugu** [mono/VulkanSharp#74]
I've been following the [Vulkan Tutorial](https://vulkan-tutorial.com) and I implemented an index buffer and noticed that it does not draw my vertices correctly. It seems to be drawing in the reverse order. 
My vertices
```C#
private Vertex[] vertices = new Vertex[]
{
	new Vertex(new float[] { -0.5f, -0.5f }, new float[] { 1.0f, 1.0f , 1.0f }),
	new Vertex(new float[] {  0.5f, -0.5f }, new float[] { 255/255f, 0.0f , 100/255f }),
	new Vertex(new float[] {  0.5f,  0.5f }, new float[] { 0.0f, 1.0f , 1.0f }),
};
```
My indices
```C#
private readonly int[] indices = new[]
{
	0, 1, 2
};
```

Everything draws correctly when using `CmdDraw`, but it wont draw properly (with the correct front face) when I use `CmdDrawIndexed` unless i reverse my indices.

Here is the full code:
[Command Buffers](https://github.com/TheDarkVoid/Meteora/blob/master/Meteora/View/MeteoraTriangleView.cs#L96)
[Initialize](https://github.com/TheDarkVoid/Meteora/blob/master/Meteora/View/MeteoraViewBase.cs#L63)
[Pipeline Creation](https://github.com/TheDarkVoid/Meteora/blob/master/Meteora/View/MeteoraViewBase.cs#L335)
[Vertex/Index Buffer Creation](https://github.com/TheDarkVoid/Meteora/blob/master/Meteora/View/MeteoraTriangleView.cs#L120)

I'm not sure why it's not working, I couldn't find any obvious errors with my code, so I decided to post here.

**Comment by TillAlex** [comment]
The indices array in your post differs from that in your code. Which one are you using?

**Comment by TheDarkVoid** [comment]
The ones I posted, the ones in my code is the reversed order to try to make sense of what may be happening, but I was only able to get one triangle rendered with that method.

**Comment by TillAlex** [comment]
I think the problem is in this line:

commandBuffers[i].CmdBindIndexBuffer(indexBuffer, 0, IndexType.Uint16);

You are using an int array for indices. The IndexType should be Int32 in this case. You could also change the array to ushort[].
