### ISSUE TITLE
Can't find Command

### ISSUE THREAD

**Issue by ROAARKNGLn** [mono/VulkanSharp#75]
i installed VulkanSharp trough the nuget package and i Can't find where EnumeratePhysicalDevices()
pls help me

**Comment by ROAARKNGLn** [comment]
please anyone?????

**Comment by TillAlex** [comment]
It's a function of the Instance class:

var instance = new Instance(new InstanceCreateInfo());
var physicalDevices = instance..EnumeratePhysicalDevices();

**Comment by ROAARKNGLn** [comment]
thank you very much
just one more question when i try to create device it says it needs arguments but doesn't tell me 
which arguments to insert how can i find them?

is there some kind of documentation? because i found the doc folder but couldnt make anything from the xml files..

**Comment by ROAARKNGLn** [comment]
or anyone else who knows how to view/read it.. can explain to me how?

**Comment by TillAlex** [comment]
I think you should better read the documentation of the Vulkan API itself. The only difference with VulkanSharp is that methods taking instances or devices as arguments in the Vulkan API are member functions of instances or devices in VulkanSharp. If you don't find a method use the search function of GitHub and search for the method name (vkEnumeratePhysicalDevices => EnumeratePhysicalDevices) to see which classes member it is.
