### ISSUE TITLE
Invalid reference in SwapchainCreateInfoKhr

### ISSUE THREAD

**Issue by FluffyStuff** [mono/VulkanSharp#8]
The **ImageExtent** field in the **Interop.SwapchainCreateInfoKhr** structure needs to be of type **Extent2D**, instead of an **IntPtr** to an **Extent2D**.

Unfortunately this isn't yet documented in the official spec, but it is in accordance with other source code I have found, and after testing it myself.

**Comment by radekdoulik** [comment]
Fixing that now, it is also mentioned in the https://github.com/mono/VulkanSharp/blob/master/tools/Generator/NOTES.txt#L9

I am now creating simple sample for Android and fixing everything along the way.
