### ISSUE TITLE
State of VulkanSharp

### ISSUE THREAD

**Issue by clSharp** [mono/VulkanSharp#80]
Currently it seems that there is no further development or bugfixing for VulkanSharp. Issues are not commented for some time now. The generator does not work for current vk.xml. 

That's why I wanted to ask: What are the plans for VulkanSharp? Will there be any further work on it or should I switch to one of the other vulkan wrappers?

It's not that I want to force anyone to work on VulkanSharp and I totally understand that open source projects are lots of work. I really appreciate all the work that has been put into this project. I just need to know which project is most promising for the future.

**Comment by radekdoulik** [comment]
The next thing I plan to work on is Vulkan 1.1 support, so that we have it available for Xamarin Android.

I would like to have it ready in about a month. Depends how much time I can squeeze in between the Xamarin Android work.

**Comment by clSharp** [comment]
Great to hear that VulkanSharp is under active development. Don't feel pushed by me. Just wanted to know if I have to look for alternatives on the long run. But now I am happy to know I don't have to invest that time. Thanks!

**Comment by MaikBusch78** [comment]
Hello Radek, yust a few days ago I have committed an update to Vulkan 1.1.87 in my fork. Maybe you want to use it. This is my fork: https://github.com/MaikBusch78/VulkanSharp
